# Generated by cpp11: do not edit by hand

InPoly_cpp <- function(xx, yy, px, py) {
  .Call(`_plover_InPoly_cpp`, xx, yy, px, py)
}

InPoly_clipper <- function(xx, yy, px, py, xyeps) {
  .Call(`_plover_InPoly_clipper`, xx, yy, px, py, xyeps)
}

inside_loop_x_y <- function(xx, yy, lpx, lpy, xyeps) {
  .Call(`_plover_inside_loop_x_y`, xx, yy, lpx, lpy, xyeps)
}

inside_point_cull <- function(xx, yy, extents) {
  .Call(`_plover_inside_point_cull`, xx, yy, extents)
}

inside_loop_mat <- function(xx, yy, lpxy, xyeps) {
  .Call(`_plover_inside_loop_mat`, xx, yy, lpxy, xyeps)
}
